version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/zaakbrug-nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 9000:9000
    depends_on:
      - zaakbrug

  zaakbrug:
    extends:
      file: docker-compose.yaml
      service: frank
    build:
      context: .
      args:
        FF_VERSION: ${FF_VERSION:-9.0.0-20241026.042336}
    image: wearefrank/zaakbrug:${ZAAKBRUG_VERSION:-latest}
    container_name: zaakbrug.dev
    environment:
      zaakbrug.zds.timezone: UTC
      # GC_LOGGING_ENABLED: true
      JAVA_OPTS: $JAVA_OPTS -XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0
      # dtap.side: EP
      configurations.Translate.classLoaderType: ScanningDirectoryClassLoader
    develop:
      watch:
        - action: sync+restart
          path: ./src/main/configurations/Translate/DeploymentSpecifics.properties
          target: /opt/frank/configurations/Translate/DeploymentSpecifics.properties
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 8080:8080
      - 9010:9010

  soapui-testrunner:
    profiles:
      - soapui
    image: smartbear/soapuios-testrunner:latest
    container_name: soapui-testrunner
    volumes:
      - ./src/main/configurations/Translate/Common/xsd/Zaak_DocumentServices_1_1_02:/zaakbrug/src/main/configurations/Translate/Common/xsd/Zaak_DocumentServices_1_1_02
      - ./e2e/SoapUI/zaakbrug-e2e-soapui-project.xml:/zaakbrug/e2e/SoapUI/zaakbrug-e2e-soapui-project.xml
      - ./e2e/reports:/reports
    environment:
      - COMMAND_LINE=-f/%reports% '/zaakbrug/e2e/SoapUI/zaakbrug-e2e-soapui-project.xml' -a -A -j -r
    depends_on:
      zaakbrug:
        condition: service_healthy
    network_mode: host

volumes:
  frank-logs:
  frank-h2db-data:

networks:
  zaakbrug-stack:
  zaakbrug-backend:
